apiVersion: v1
kind: Service
metadata:
  name: hermes
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/part-of: hermes
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: hermes
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
