apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hermes
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/part-of: hermes
    app.kubernetes.io/component: web
spec:
  to:
    kind: Service
    name: hermes
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
