apiVersion: v1
kind: Secret
metadata:
  name: hermes-secret
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/part-of: hermes
    app.kubernetes.io/component: web
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
